### ISSUE TITLE
Support for Gravatar

### ISSUE THREAD

**Issue by dwilson390** [samerton/NamelessMC#68]
Hey, Just wondering about the possibility of Gravatar support, it's not overly hard to implement.  Developer resources are located here; https://en.gravatar.com/site/implement/

**Comment by samerton** [comment]
I'll try and get this in for 1.0, thanks for the suggestion!

**Comment by dwilson390** [comment]
Great thanks! :)

**Comment by samerton** [comment]
Added in the last two commits in the new repository ([1](https://github.com/NamelessMC/Nameless/commit/60f2f0ed2a39ac36752ba7bd794bca53ff2bc78c), [2](https://github.com/NamelessMC/Nameless/commit/ed3d64074c8954455374678a0733597e398acabc)). It's worth holding on until the full 1.0 release instead of applying the commit manually though, to avoid any database issues.
