### ISSUE TITLE
Sub-Fourms dont work on Pre Release 3

### ISSUE THREAD

**Issue by CodingConnor** [samerton/NamelessMC#94]

**Comment by samerton** [comment]
Hi,

This has since been fixed (in [this commit](https://github.com/NamelessMC/Nameless/commit/353dae5409b8316d7473a8fad57a8bb75dde17a1#diff-18611b6789f56593d72426dce947bcfe)), and it will be included in pre release 4 :)

To apply the fix now, you can edit **modules/Forum/pages/view_forum.php** in a text editor, remove all code inside, and replace it with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/353dae5409b8316d7473a8fad57a8bb75dde17a1/modules/Forum/pages/forum/view_forum.php).
